export function milesBetween(a,b){const r=Math.PI/180,dlat=(b[0]-a[0])*r,dlon=(b[1]-a[1])*r;const h=Math.sin(dlat/2)**2+Math.cos(a[0]*r)*Math.cos(b[0]*r)*Math.sin(dlon/2)**2;return 3958.7613*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
export function visibleParks(parks,{query='',filter='all',savedOnly=false,saved=[],sort='recommended',origin}={}){const q=query.trim().toLowerCase();const result=parks.filter(p=>(filter==='all'||(filter==='photos'?Boolean(p.photos?.length):p.types.includes(filter)))&&(!savedOnly||saved.includes(p.id))&&(!q||[p.name,p.fullName,p.town,...p.tags,p.features].join(' ').toLowerCase().includes(q)));if(sort==='distance'&&origin)result.sort((a,b)=>milesBetween(origin,[a.lat,a.lon])-milesBetween(origin,[b.lat,b.lon]));return result;}
export function localDate(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
export function addDays(date,days){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
export function initialTripDate(now=new Date()){const today=localDate(now);return today<='2026-09-10'?'2026-09-10':today;}
export function dateLabel(date){return new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));}
export function directionsUrl(park,provider='google'){const coordinates=`${park.lat},${park.lon}`,destination=park.community?coordinates:park.fullName+', '+park.address;if(provider==='apple')return 'https://maps.apple.com/?'+new URLSearchParams({daddr:park.community?coordinates:park.address,dirflg:'d'});return 'https://www.google.com/maps/dir/?'+new URLSearchParams({api:'1',destination,travelmode:'driving'});}
export function osmSkateparkQuery({south,west,north,east}){const values=[south,west,north,east].map(Number);if(values.some(value=>!Number.isFinite(value)))throw Error('Invalid map bounds');const [s,w,n,e]=values;if(s>=n||w>=e||s < -85||n > 85||w < -180||e > 180)throw Error('Invalid map bounds');const box=values.map(value=>value.toFixed(5)).join(',');return `[out:json][timeout:18][maxsize:67108864];(nwr["sport"~"(^|;)skateboard(;|$)"](${box});nwr["leisure"~"^skate_?park$"](${box});nwr["amenity"~"^skate_?park$"](${box}););out center tags qt;`;}
export function normalizeOsmSkatepark(element){const tags=element?.tags||{},sport=String(tags.sport||'').split(';').map(value=>value.trim()),explicit=/^skate_?park$/i.test(tags.leisure||'')||/^skate_?park$/i.test(tags.amenity||''),hasVenue=Boolean(tags.leisure||tags.amenity||tags.indoor==='yes'||tags.club==='sport'||tags.building==='sports_hall');if((!explicit||['shop','office','craft'].some(key=>tags[key]))&&!(sport.includes('skateboard')&&hasVenue))return null;if(['disused:leisure','abandoned:leisure','demolished:leisure','removed:leisure','was:leisure'].some(key=>tags[key]))return null;const lat=Number(element.lat??element.center?.lat),lon=Number(element.lon??element.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon)||!['node','way','relation'].includes(element.type)||!Number.isInteger(Number(element.id)))return null;const mappedName=String(tags.name||tags['name:en']||'').trim(),name=mappedName||'Mapped skatepark',town=String(tags['addr:city']||tags['addr:town']||tags['addr:village']||tags['addr:place']||'Community mapped').trim(),facts=[];if(tags.surface)facts.push(`Surface: ${tags.surface}`);if(tags.indoor==='yes'||tags.covered==='yes')facts.push('Indoor / covered');if(tags.skatepark)facts.push(`Mapped features: ${tags.skatepark}`);const accessValue=String(tags.access||'').trim(),addressParts=[tags['addr:housenumber'],tags['addr:street'],tags['addr:city']||tags['addr:town'],tags['addr:state'],tags['addr:postcode']].filter(Boolean);return {id:`osm-${element.type}-${element.id}`,osmKey:`${element.type}/${element.id}`,community:true,name,fullName:name,town,lat,lon,address:addressParts.length?addressParts.join(', '):`${lat.toFixed(6)},${lon.toFixed(6)}`,types:[tags.indoor==='yes'||tags.covered==='yes'?'indoor':'community'],tags:['Community mapped',...(tags.surface?[String(tags.surface)]:[]),...(tags.indoor==='yes'||tags.covered==='yes'?['Indoor']:[])],features:facts.length?facts.join('. ')+'.':'Feature inventory is not listed in the map data.',why:'This skatepark is mapped in OpenStreetMap and appeared in the current map view. It has not received the full SESSION research review yet.',note:'Community map data can be incomplete or stale. Check signs, access and conditions when you arrive.',hours:tags.opening_hours||'Hours not listed',hoursNote:'Opening status has not been independently verified.',access:accessValue?`OpenStreetMap access: ${accessValue}`:'Access not independently verified',cost:'Fee not listed',phone:null,photos:[],sources:[[`OpenStreetMap ${element.type} ${element.id}`,'Live community-mapped location and tags',`https://www.openstreetmap.org/${element.type}/${element.id}`]]};}
export function readSaved(raw,parks){try{const value=JSON.parse(raw);return Array.isArray(value)?[...new Set(value)].filter(id=>parks.some(p=>p.id===id)):[];}catch{return [];}}
export function hourlyForDate(data,date){const h=data?.hourly;if(!h||!Array.isArray(h.time))return [];return h.time.flatMap((time,i)=>time.startsWith(date)&&Number.isFinite(h.temperature_2m?.[i])&&Number.isFinite(h.precipitation_probability?.[i])?[{time,hour:Number(time.slice(11,13)),temp:h.temperature_2m[i],rain:h.precipitation_probability[i],amount:h.precipitation?.[i]??null,wind:h.wind_speed_10m?.[i]??null,code:h.weather_code?.[i]??null}]:[]);}
export function sessionSummary(hours){const daytime=hours.filter(x=>x.hour>=9&&x.hour<=18);if(!daytime.length)return null;const rainMax=Math.max(...daytime.map(x=>x.rain)),high=Math.max(...daytime.map(x=>x.temp));let best=null;for(let i=0;i<daytime.length-2;i++){const window=daytime.slice(i,i+3);if(window[2].hour-window[0].hour!==2)continue;const score=window.reduce((s,h)=>s+h.rain,0)/3;if(!best||score<best.score)best={start:window[0].hour,end:window[2].hour+1,score};}return {high,rainMax,best};}
export function hourLabel(hour){return `${hour%12||12}${hour>=12?'pm':'am'}`;}
export function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
